add-search
enjsite/java-filmorate pull request #16
Opened 2023-05-02 14:03 UTC by GeiseR98

2023-05-02 16:45 UTC, stgmakarov commented on src/main/java/ru/yandex/practicum/filmorate/storage/SearchDbStorage.java
> +    public List<Film> getSearch(String query, String searchBy) {
Такой вариант запроса уязвим к атаке типа SQL Injection. Если сформировать специальным образом строку поиска, то можно получить доступ к БД в обход проверки полномочий. Лучше передавать параметры запроса через "?" или, как вариант, удалять из строки поиска спец символы (но это сложнее). Ревьювер, скорее всего, тоже обратит внимание. Подробнее можно почитать, например, тут https://habr.com/ru/articles/148151/

2023-05-02 16:59 UTC, Tulpanchik2906 approved these changes

2023-05-02 16:59 UTC, Tulpanchik2906 commented on src/main/java/ru/yandex/practicum/filmorate/storage/SearchDbStorage.java
> +public class SearchDbStorage implements SearchStorage {
Я бы эту функциональность отнесла бы к FilmDBStorage, потому что по итогу получается список фильмов.

2023-05-02 16:59 UTC, Tulpanchik2906 commented on src/main/java/ru/yandex/practicum/filmorate/storage/SearchDbStorage.java
> +        List<String> requestParam = List.of(searchBy.split(","));
Мне кажется,что где-то либо здесь, либо в контроллере стоит добавить проверки  на null для полей query и searchBy и явно возвращать и логировать ошибку

2023-05-02 17:34 UTC, enjsite requested changes

2023-05-02 17:34 UTC, enjsite commented on src/main/java/ru/yandex/practicum/filmorate/storage/SearchStorage.java
> +public interface SearchStorage {
Думаю, не стоит выносить эти методы в отдельный Storage, по сути поиск к сущности Фильмы относится, лучше там и оставить.

2023-05-02 17:34 UTC, enjsite commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        filmController = new FilmController(new FilmService(new InMemoryFilmStorage(), null, null, null));
И тогда не придется в этом месте ничего добавлять в конструктор)

2023-05-03 19:07 UTC, enjsite approved these changes

2023-05-03 19:07 UTC, merged