TZ12 feat: Develop
enjsite/java-filmorate pull request #18
Opened 2023-05-04 07:55 UTC by enjsite

2023-05-05 11:45 UTC, zgreen3 requested changes
Привет! Вы проделали большую работу! 
У вас получился отличный проект и появились навыки работы в команде а также перекрёстных ревью кода внутри команды (насколько могу судить из истории пулл-реквестов, это была также плодотворная часть вашей работы)). 
Молодцы, что совместно сделали практически все возможные задания (поскольку не нашёл описания общего пулл-реквеста в ветку main и данных об этом в файле readme.md проекта, судил об этом по названию веток, комментариям в пулл-реквестах в ветку develop и по коду самого проекта - в будущих командных проектах важно описывать их функционал и структуру, хотя бы парой фраз, как и редкие технические решения, при их наличии, в файле readme.md - никогда не знаешь, кому передадут проект "по наследству", а такой файл может снять сразу множество вопросов)!
Вы хорошо разобрались во взаимодействие между слоями "контроллер", "сервис", "репозиторий" и в том, как добавлять новый функционал в эту трёхзвенную архитектуру.  
У вас получились отличные запросы к таблицам (с использованием вложенных запросов, но не более, чем на 1 уровень в глубину, и даже с применением аналитических функций), хотя возможны отдельные оптимизации (какие именно я указал в комментариях в гите). 
Также хочу заметить, что к тестовым классам важно относиться как к полноценным классам проекта, т.е. не пренебрегать стилистическими деталями (например, удалять неиспользуемый код при пулл-реквестах в общие ветки проекта, определять оптимальные в каждом конкретном случае области видимости полей, и т.п., это поможет не вносить в юнит-тесты случайные трудноуловимые ошибки в будущем). 
Обращаю внимание, что в REST-эндпоинтах (даже с типом POST, PUT и DELETE) с синхронной обработкой (асинхрную вы пока не проходили, поэтому пока можно считать, что во всех)) желательно возвращать не константный результат, а полноценное сообщение о статусе ответа, т.к. на этапе работы методов в сервисах и репозиториях не исключены всевозможные сбои в работе и клиенту важно понимать, если они имели место, т.е. не получать в таких случаях одно и то же сообщение о том, что нужное действие сервером произведено.
После учёта комментариев и (или) возможных изменений в коде на их основе, присылайте работу на продолжение проверки.
Спасибо.

2023-05-05 11:45 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                "FILM_ID IN ( SELECT FILM_ID FROM LIKES WHERE USER_ID = ? ))\n" +
Надо исправить:
Могу ошибаться (не было возможности запустить проект с БД для проверки), но здесь вложенный запрос 2-го уровня выглядит излишним: отбор фильмов по ИД пользователя уже производится в таблице лайков на сточку выше, на 387 строке. 
Проверьте, пожалуйста, этот момент и удалите лишний запрос (всю данную строчку 388 из фильтра внешнего к данному select-запроса) или аргументируйте необходимость его наличия здесь.
Комментарий указал как "Надо исправить", потому что в бэкенд-проектах работа с БД обычно очень чувствительная для производительности всего приложения тема и ей всегда важно уделять повышенное внимание=).

2023-05-05 11:45 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                "     EXCEPT SELECT film_id\n" +
Можно лучше:
Обычно в движки реляционных СУБД оптимизированы для работы с JOIN-ами, а выражения по работе с множествами значений, вроде EXCEPT SELECT менее распросранены и могут выдавать неоптимальный результат на разных СУБД (особенно, если они применяются уже в конце реализации плана запроса), кроме того, иногда они сложнее воспринимаются читающим код, т.к. мысленно их нужно выполнять над мысленным результатом работы всего остального кода, а не в самом этом процессе.
Подумайте, как можно заменить EXCEPT SELECT (подсказка: на LEFT OUTER JOIN с фильтром на is null у соответствующей таблицы / подзапроса, см. пример этого, например, здесь, на англ. яз., https://stackoverflow.com/a/56859428).

2023-05-05 11:45 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        return "Лайк добавлен";
Можно лучше:
Здесь и далее в коде целесообразно возвращать сообщение о результате работы вызываемого метода сервиса (для чего, вероятно, его потребуется немного преобразовать для возврата булевых значений), т.к. в REST-эндпоинтах (даже с типом POST, PUT и DELETE) на этапе работы методов в сервисах и репозиториях не исключены всевозможные сбои в работе и клиенту важно понимать, если они имели место, т.е. не получать в таких случаях одно и то же сообщение о том, что нужное действие сервером произведено.

2023-05-05 11:45 UTC, zgreen3 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
Можно лучше:
Лишний закомментированный код (в этом файле и в файле UserControllerTest) лучше удалять даже в тестовых методах при пулл-реквестах в мастер ветку и вообще, в любые "общие" (не фичи) ветки, где работает более 1 разработчика, т.к. иногда он может совершенно неожиданно "выстрелить в ногу" (пишу на собственном подобном опыте)), если попадает в распоряжение к другим разработчикам.

2023-05-05 11:45 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserDbStorage.java
> +        if (jdbcTemplate.queryForObject(checkQuery, Integer.class, id) == 0) {
Можно лучше:
Здесь важно добавить проверку результата на null до проверки на 0, т.к. возвращаемое значение этого метода будет классом Integer, который может быть null (см., например, пояснение на англ. яз., https://stackoverflow.com/a/74433112).

2023-05-05 12:41 UTC, Tulpanchik2906 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                "FILM_ID IN ( SELECT FILM_ID FROM LIKES WHERE USER_ID = ? ))\n" +
Так сделано специально, иначе у меня терялись пустые строки

2023-05-05 19:25 UTC, Tulpanchik2906 approved these changes

2023-05-06 10:31 UTC, zgreen3 approved these changes
Привет, вижу, что вы учли все важные комментарии, отлично (вижу по истории коммитов, что вчера вечером и даже ночью было приложено достаточно сил для этого, такая целеустремлённость вызывает уважение)!
Принимаю проект в текущем виде, встретимся на проверке следующих проектов.
Успехов в обучении!

2023-05-06 10:31 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +        String sqlReq = "SELECT FILM_ID AS ID\n" +
Отлично (и немного "Можно лучше"):
Вижу, что запрос упростился: убран left join и данные об ИД фильмов теперь получаются напрямую из таблицы лайков, т.к. возможно считать лайки через подсчёт числа пользователей (их ИД) для каждого из фильмов в таблице лайков, на что я не обратил внимание при предыдущей итерации ревью - вы сами это заметили и оптимизировали, круто!

При этом в оптимизированном коде остался подзапрос
```
"  AND (FILM_ID in\n" +
"         (SELECT FILM_ID\n" +
"          FROM LIKES\n" +
"          WHERE USER_ID = ?))\n" + 
```
, необходимость наличия которого для меня всё ещё не очевидна. 
При предыдущей итерации код-ревью я не обратил в этом месте ваше внимание (сам тогда про это не подумал, сейчас исправляюсь)), что нужно попробовать не просто удалить этот подзапрос, а заменить его на фильтр `user_id = ... AND film_id IS NOT NULL`, чтобы получить эквивалентный (только в данном конкретном select-е!) выражению `user_id = ... AND film_id IN (...)` фильтр, который не будет возвращать строки, где film_id может быть null. В любом случае, этот вопрос не настолько важен для обучения, чтобы конкретно из-за него проводить ещё одну итерацию код-ревью =().

2023-05-06 10:31 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmDbStorage.java
> +                "WHERE USER_ID = ?\n" +
Можно лучше:
В синтаксисе sql-запросов обычно принято сами команды (ключевые слова языка SQL) писать заглавными буквами, чтобы их было видно во всём запросе, а имена переменных - прописными.

2023-05-06 10:31 UTC, zgreen3 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public boolean deleteById(@PathVariable Integer id) {
Можно лучше:
Отлично, что вы изменили возвращаемые значения на уровне сервиса и репозитория!

На уровне контроллера можно (и даже желательно, т.к. API могут использовать клиенты, которые не в курсе того, что будет означать возвращаемое булево значение) оставить возврат строк / Stringв тело http-ответов (т.е. как возвращаемые значения методов контроллера в Spring Boot), просто текст возвращаемого сообщения можно сделать разным - в зависимости от булева значения из метода сервиса (успех или ошибка).

2023-05-09 08:35 UTC, merged